version: "3.9"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "${DB_PORT}:1433"
    volumes:
      - mssqldata:/var/opt/mssql

  nlp:
    build:
      context: .
    container_name: nlp
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URI: >
        mssql+pyodbc://${DB_USER}:${SA_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?driver=${SQL_DRIVER}
    ports:
      - "5000:5000"
    command: ["python", "app.py"]

volumes:
  mssqldata:
