// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheMeaningDiscordancy.Infrastructure.Data;

#nullable disable

namespace TheMeaningDiscordancy.Infrastructure.Migrations
{
    [DbContext(typeof(DiscordContext))]
    partial class DiscordContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TheMeaningDiscordancy.Infrastructure.Models.Entities.ItemEfc", b =>
                {
                    b.Property<Guid>("ObjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectKey");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TheMeaningDiscordancy.Infrastructure.Models.Entities.SeedEfc", b =>
                {
                    b.Property<Guid>("ObjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeedId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ObjectKey");

                    b.ToTable("Seeds");
                });

            modelBuilder.Entity("TheMeaningDiscordancy.Infrastructure.Models.Entities.TagEfc", b =>
                {
                    b.Property<Guid>("ObjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ObjectKey");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("TheMeaningDiscordancy.Infrastructure.Models.Entities.ThemeEfc", b =>
                {
                    b.Property<Guid>("ObjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("ObjectKey");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("TheMeaningDiscordancy.Infrastructure.Models.Entities.SeedEfc", b =>
                {
                    b.OwnsOne("TheMeaningDiscordancy.Infrastructure.Models.Entities.ThemeVectorEfc", "ThemeVector", b1 =>
                        {
                            b1.Property<Guid>("ObjectKey")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("CreationAxis")
                                .HasColumnType("real");

                            b1.Property<float>("DivineAxis")
                                .HasColumnType("real");

                            b1.Property<float>("OrderAxis")
                                .HasColumnType("real");

                            b1.Property<Guid>("SeedId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<float>("UnityAxis")
                                .HasColumnType("real");

                            b1.HasKey("ObjectKey");

                            b1.ToTable("Seeds");

                            b1.WithOwner()
                                .HasForeignKey("ObjectKey");
                        });

                    b.Navigation("ThemeVector")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
